function Course(course, technology, classify, description, price, score, attention, teacher, imgCover, img, nodus) {
	this.course = course;
	this.technology = technology;
	this.classify = classify;
	this.description = description;
	this.price = price;
	this.score = score;
	this.attention = attention;
	this.teacher = teacher;
	this.imgCover = imgCover;
	this.img = img;
	this.nodus = nodus;
}

/**
 * [aCourse 课程包对象数组]
 * @type {Array}
 */
var aCourse = [
	/*-------------------------------------------------------------------------前端开发方向-------------------------------------------------------------------------*/
	{"course":"移动web开发适配秘籍Rem","technology":"前端开发","classify":"HTML/CSS","description":"简介：移动web开发适配的方案有许多，然而最好的方案一定要掌握。本课程主要讲解移动web开发中常见的适配方法，着重讲解使用rem方案的原理和使用方法，来进行移动web开发的适配工作，借助于实战页面让学者更加清晰的掌握实战工作中如何应用rem适配技术。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg1.jpg","nodus":"初级"},
	{"course":"css定位 position","technology":"前端开发","classify":"HTML/CSS","description":"简介：本课程，将带领大家了解一下定位的知识，教大家如何通过定位来进行布局。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg2.jpg","nodus":"初级"},
	{"course":"基于websocket的火拼俄罗斯（单机版）","technology":"前端开发","classify":"HTML/CSS","description":"简介：本课程是基于websocket的火拼俄罗斯的升级版本，课程中在前两个课的基础上实现了用两个浏览器对战模式，完整的实现了游戏的过程。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg3.jpg","nodus":"中级"},
	{"course":"前端性能优化-通用的缓存SDK","technology":"前端开发","classify":"HTML/CSS","description":"简介：性能优化成神之路的必看之课，是前端性能优化基础简介的后续篇章，作为一门前端性能优化的进阶课程，本课程介绍了常用的性能优化方法，以及老师自己在工作中摸索出来的，并且在大厂使用的课程。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg4.jpg","nodus":"中级"},
	{"course":"Handlebars模板引擎","technology":"前端开发","classify":"HTML/CSS","description":"简介：本课程介绍了Handlebars.js渲染页面的常用方式，如#each、#if等，以及在使用Handlebars.js渲染页面时的写作技巧，不仅有思想的引导，更有代码的优化。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg5.jpg","nodus":"高级"},
	{"course":"DatePicker组件开发","technology":"前端开发","classify":"HTML/CSS","description":"简介：通过原生HTML/CSS/JavaScript完成一个日期选择器（datepicker）组件的开发。主要包括datepicker静态结构的编写、日历数据的计划获取、组件的渲染以及组件事件的处理。 课程基本涵盖一个完整的前端组件的基本要素，掌握后对其它组件的开发有借鉴意义。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg6.jpg","nodus":"高级"},
	{"course":"ES6快速入门","technology":"前端开发","classify":"JavaScript","description":"简介：ES6增加了很多新的语法，很多同学学习起来感觉很别扭，有时候也不理解新增加的语法有什么用，对ES6的学习也没有兴趣进而动力不足、学习效率不高。本课程通过ES3、ES5、ES6的对比去实现同一个问题，学员可以非常容易的理解和掌握ES6的强大并产生学习的兴趣。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg7.jpg","nodus":"初级"},
	{"course":"Promise 入门","technology":"前端开发","classify":"JavaScript","description":"简介：为解决异步函数的回调陷阱，开发社区不断摸索，终于折腾出 Promise/A+。它的优势非常显著： 1. 不增加新的语法，可以立刻适配几乎所有浏览器 2. 以队列的形式组织代码，易读好改 3. 捕获异常方案也基本可用","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg8.jpg","nodus":"中级"},
	{"course":"Javascript实现二叉树算法","technology":"前端开发","classify":"JavaScript","description":"简介：Javascript发展越来越快，并且将触角延伸到各个领域，几乎有一统江湖之势。无论是前端，后台服务器，移动开发，Javascript无不占据着重要位置，学习和使用Javascipt这门编程语言是性价比最高的，学习Javascript算法也相当重要的。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg9.jpg","nodus":"高级"},
	{"course":"移动web开发适配秘籍Rem","technology":"前端开发","classify":"CSS3","description":"简介：移动web开发适配的方案有许多，然而最好的方案一定要掌握。本课程主要讲解移动web开发中常见的适配方法，着重讲解使用rem方案的原理和使用方法，来进行移动web开发的适配工作，借助于实战页面让学者更加清晰的掌握实战工作中如何应用rem适配技术。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg10.jpg","nodus":"初级"},
	{"course":"HTML5+CSS3实现春节贺卡","technology":"前端开发","classify":"CSS3","description":"简介：以春节为主题，通过一个简单的春节手机端祝贺页面的实例演示，并通过对案例进行拆分和讲解，让您对手机端简易网站从零建站有一个简单的认识，并让您可以独立开发简单的手机端小型展示网页。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg11.jpg","nodus":"中级"},
	{"course":"CSS3+JS 实现超炫的散列画廊特效","technology":"前端开发","classify":"CSS3","description":"简介：在网页中传统的照片查看一直是网格-列表，现在我们可以突破这种限制，获得和现实中一样的自由。随意摆放的照片，超酷的切换动画；还能翻开照片，查看图片简介。 本课程主要有两个部分；前半部分以原理分析和前端界面实现为主，后半部分则是脚本来处理的一些特效与总结。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg12.jpg","nodus":"高级"},
	{"course":"入门微信小程序开发","technology":"前端开发","classify":"Html5","description":"简介：讲解微信小程序的基本知识，如何注册，并开发一个自己的小程序，以及小程序开发过程中部分常见的问题。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg13.jpg","nodus":"初级"},
	{"course":"H5+JS+CSS3 实现圣诞情缘","technology":"前端开发","classify":"Html5","description":"简介：圣诞节将近，帅哥美女相约，送一份特别的礼物，让TA过一个不一样的节日。本课程中使用面向对象的编程方式，采用H5+JS+CSS3的混合使用实现整个功能。课程当中总共分为3个主题场景图，多个精灵图以及雪碧图，实现了静与动的完美结合，并且由浅入深的将整个案例拆分讲解。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg14.jpg","nodus":"中级"},
	{"course":"HTML5+CSS3实现春节贺卡","technology":"前端开发","classify":"Html5","description":"简介：以春节为主题，通过一个简单的春节手机端祝贺页面的实例演示，并通过对案例进行拆分和讲解，让您对手机端简易网站从零建站有一个简单的认识，并让您可以独立开发简单的手机端小型展示网页。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg15.jpg","nodus":"高级"},
	{"course":"JS/jQuery宽高的理解和应用","technology":"前端开发","classify":"jQuery","description":"简介：js和jquery中各式各样的宽高有很多。平时用的也蛮多，但是有时候我们会把某些宽高的用法和使用场景混淆，本套课程帮大家理清js和jquery的各种宽高，并和大家一起对宽高做一些简单的应用。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg16.jpg","nodus":"初级"},
	{"course":"jQuery基础(五)一Ajax应用与常用插件","technology":"前端开发","classify":"jQuery","description":"简介：本课程介绍如何用jquery实现ajax应用，深入理解jQuery框架提供的各类API与函数的工作原理和自定义jQuery插件的各项技能。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg17.jpg","nodus":"中级"},
	{"course":"jQuery源码解析（DOM与核心模块）","technology":"前端开发","classify":"jQuery","description":"简介：本课程是目前真正意义上第一部完整的jQuery 2.1.1版本源码课程，课程共14章，分两个部分，本课程是第一部分课程。本课程主要讲解DOM处理与核心模块部分，可以让我们由浅入深的剖析jQuery库的设计与实现。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg18.jpg","nodus":"高级"},
	/*-------------------------------------------------------------------------End 前端开发方向-------------------------------------------------------------------------*/

	/*-------------------------------------------------------------------------后端开发方向-------------------------------------------------------------------------*/
	{"course":"Python实现线性回归","technology":"后端开发","classify":"Python","description":"简介：对于机器学习的入门学习者提供线性回归的原理讲解，在掌握原理的基础上，利用python实现最小二乘法或者梯度下降来进行线性回归分析。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg19.jpg","nodus":"初级"},
	{"course":"python自动化运维篇","technology":"后端开发","classify":"Python","description":"简介：随着技术的进步、业务需求的快速增长，一个运维人员通常要管理上百、上千台服务器，运维工作也变的重复、繁杂。把运维工作自动化，能够把运维人员从服务器的管理中解放出来，让运维工作变得简单、快速、准确","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg20.jpg","nodus":"中级"},
	{"course":"Python-走进Requests库","technology":"后端开发","classify":"Python","description":"简介：通过requests类库的学习，理解HTTP基本原理，并能够纯熟地使用requests和Github API进行数据交互。除此之外，你还能够获得诸如HTTP认证，Oauth授权等进阶知识和技能.","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg21.jpg","nodus":"高级"},
	{"course":"PhpStorm的基本应用","technology":"后端开发","classify":"PHP","description":"简介：PhpStorm是PHP集成开发工具，能提高我们的开发效率，提供智能代码补全，快速导航以及即时错误检查。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg22.jpg","nodus":"初级"},
	{"course":"CDN与智能DNS原理和应用","technology":"后端开发","classify":"PHP","description":"简介：CDN是内容分发网络，利用部署大量网络节点，通过服务器缓存加速，让用户可以就近同运营商网络，更快的访问到我们的互联网产品，可以简单快速的让我们的互联网产品支持海量的并发请求。智能DNS比传统DNS更好的地方就是能够基于IP信息给不同的用户最合适的服务器IP，可以给用户提供更好的网络服务。本课程详细讲解了CDN的原理和具体使用，也有详细介绍DNS解析的完整过程，再具体介绍了智能DNS的实现原理和作用，让大家对这些基础服务有更加深入的了解。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg23.jpg","nodus":"中级"},
	{"course":"web安全之SQL注入","technology":"后端开发","classify":"PHP","description":"简介：SQL注入自从WEB和数据库发展以来就一直存在，而且给WEB应用带来很大的安全问题，会造成用户隐私数据的泄露，数据库版本信息泄露和数据库攻击等，给业务带来很大的损失和不好的社会影响。所以对于我们WEB开发人员来说，项目开发过程中一定要培养一定的安全意识，了解SQL注入的定义，产生的原理、具体的一些攻击手法和相应的预防措施，为了更好的增加开发项目的健壮性和安全性","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg24.jpg","nodus":"高级"},
	{"course":"SpringBoot开发常用技术整合","technology":"后端开发","classify":"JAVA","description":"简介：本课程通过详细的对springboot的各个技能点逐一介绍与演示，可以很迅速的熟悉整个springboot框架体系，并且与springmvc有效的进行对比，理解异同，这样对于后续的springboot开发会非常迅速。同时课程中会针对不同的技术点进行不同的应用场景的讲解，使得学生更好的理解未来自己做项目中如何运用。另外老师的分布式课程课程《ZooKeeper分布式专题与Dubbo微服务入门》已经上线，需要的小伙伴一定不要错过~","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg25.jpg","nodus":"初级"},
	{"course":"基于SpringBoot 十分钟搞定后台管理平台","technology":"后端开发","classify":"JAVA","description":"简介：大道至简系列课程，旨在为大家指明技术发展路径，以实际项目为背景，阐述“那些年\"遇到的\"坑\"，并从零到实战逐步\"排雷\"。 本次课程作为大道至简的基础篇，会为大家阐述Guns框架的，并且带领大家，在较短的时间内，快速搭建一个属于个人的后台管理系统，并且帮助大家完成快速开发的过程。老师主讲的进阶课程《Tomcat+Memcached/Redis集群 构建高可用解决方案》已上线，有兴趣的小伙伴可以来学习下","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg26.jpg","nodus":"中级"},
	{"course":"使用Google Guice实现依赖注入","technology":"后端开发","classify":"JAVA","description":"简介：本课程将带领大家通过Google Guice来系统的学习DI思想中的绑定，注入，生命周期，aop等方面的技巧。并示范Guice和Spring Boot如何协作。对于熟悉Spring的同学，学完本课后可以了解两者异同，加深对DI和Spring的理解。不只是为了单纯教授Gucie的用法，而是以Guice为媒介，希望使同学们在编程能力上能有所提高。 老师相关实战课程《Java校招面试》也已上线：http://coding.imooc.com/class/132.html 基础知识和编程能力是软件工程师职业生涯中长期受益的。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg27.jpg","nodus":"高级"},
	{"course":"数据结构探险之图篇","technology":"后端开发","classify":"C++","description":"简介：本课程主要以图的存储方式，图的遍历方法，图的最小生成树为内容主体，详细讲述了图的存储方式，图的遍历和最小生成树的编程思路及实现原理，并手把手完成图的深度优先遍历算法和广度优先遍历算法，","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg28.jpg","nodus":"初级"},
	{"course":"C++远征之多态篇","technology":"后端开发","classify":"C++","description":"简介：本课程将带领大家体会面向对象三大特性中的多态特性，讲述了虚函数、抽象类和接口类等概念，以及多态的实现原理，课程的最后引入RTTI及异常处理，使整个多态篇更加完整，更具实战指导性，本门课程是C++远征课程的高潮和经典，对于面向对象的语言的学习将大有裨益。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg29.jpg","nodus":"中级"},
	{"course":"Cocos2d-x游戏开发初体验-C++篇","technology":"后端开发","classify":"C++","description":"简介：游戏开发博大精深，在这个后页游时期的手游时代，还在为无法入门游戏行业而烦恼吗？Cocos2d-x就是一款专门为手机游戏打造的开源游戏引擎，够轻量、够简单。在这个不一样的时代，雷哥将带着你走出一个不一样的自己","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg30.jpg","nodus":"高级"},
	{"course":"C语言入门","technology":"后端开发","classify":"C","description":"简介：本C语言教程从以下几个模块来贯穿主要知识点：初始C程序、数据类型、运算符、语句结构、函数和数组。每个阶段都配有练习题同时提供在线编程任务。希望通过本教程帮助C语言入门学习者迅速掌握程序逻辑并开始C语言编程。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg31.jpg","nodus":"初级"},
	{"course":"Linux C语言指针与内存","technology":"后端开发","classify":"C","description":"简介：本课程通过图形与程序实验，配合gdb调试工具，将c语言编程中最难理解的内存管理与指针形象的展示在大家面前。由于内存地址的概念偏底层，想真正掌握还需按照课程中教授的方法多做实验以加深映像，相信反复试验几次之后，大家都能够对c语言有更加深刻的理解。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg32.jpg","nodus":"中级"},
	{"course":"Linux C语言编程基本原理与实践","technology":"后端开发","classify":"C","description":"简介：介绍C语言基本工作原理以及适用与C的实际开发方式，并指导童鞋们能在Linux环境下编写并运行符合实际商业开发环境下的C语言程序。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg33.jpg","nodus":"高级"},
	/*-------------------------------------------------------------------------End 后端开发方向-------------------------------------------------------------------------*/

	/*-------------------------------------------------------------------------移动开发方向-------------------------------------------------------------------------*/
	{"course":"iOS开发之网络协议","technology":"移动开发","classify":"iOS","description":"简介：本课程主要带大家了解HTTP的发展历程，熟悉HTTP的工作流程。并且还会给大家讲解HTTPS和HTTP的区别，以及HTTPS的安全性，熟悉加密算法的一个流程。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg34.jpg","nodus":"初级"},
	{"course":"iOS之分享集成","technology":"移动开发","classify":"iOS","description":"简介：本课程主要带领大家了解集成分享功能的流程，告诉大家如何注册友盟、SDK环境的配置、分享功能的实现。并且让大家掌握该如何集成第三方，后续集成其它第三方功能时就可以轻松搞定。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg35.jpg","nodus":"中级"},
	{"course":"iOS开发之传感器","technology":"移动开发","classify":"iOS","description":"简介：本课程给大家补充介绍iOS中常见的传感器，并通过图解的方式详细介绍了加速度传感器以及角速度传感器。最后通过实际的Demo源码演示并分析整个实现的过程。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg36.jpg","nodus":"高级"},
	{"course":"Android UiAutomator 2.0 入门实战","technology":"移动开发","classify":"Android","description":"简介：零基础学习使用UiAutomator 2.0自动化测试，了解框架知识，环境配置，通过学习UI自动化三要素，通过搜索条件（文件、ID、属性等）找到组件（按钮、图标、文本框等），操作组件（点击、长按、滑动、输入等），快速掌握编写Android 自动化测试用例。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg37.jpg","nodus":"初级"},
	{"course":"Android O(8.0)通知栏解决方案","technology":"移动开发","classify":"Android","description":"简介：本课程为大家介绍NotificationChannel API，Android8.0兼容适配的重要性，Android 8.0 ChannelNotification的管理，自定义ChannelNotification与交互。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg38.jpg","nodus":"中级"},
	{"course":"Android与WebView的js交互","technology":"移动开发","classify":"Android","description":"简介：本课程为大家来了WebView的使用场景及常见交互，通过讲解演示让大家掌握WebView对java方法的调用以及实现js方法的调用参数的传递，还会介绍如何使用chrome浏览器调试客户端中网页的方法，以及注意的事项，最后会为大家分析WebView的js交互中常犯的几个错误。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg39.jpg","nodus":"高级"},
	{"course":"Unity 3D基础之变体Transform","technology":"移动开发","classify":"Unity 3D","description":"简介：全面讲解 Transform 组件的基础使用方法.通过实践，实现在 Unity 中控制游戏对象移动、缩放、旋转。附带讲解一些优化相关的小知识。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/cimg40.jpg","nodus":"初级"},
	{"course":"带你开发类似Pokemon Go的AR游戏","technology":"移动开发","classify":"Unity 3D","description":"简介：带你开发类似Pokemon Go的AR游戏：课程介绍，开发环境配置，游戏场景一：有卡识别，游戏场景二：无卡识别，游戏菜单场景，导出 iOS 平台并运行，导出 Android 平台并运行，课程总结。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"中级"},
	{"course":"Unity3D快速入门","technology":"移动开发","classify":"Unity 3D","description":"简介：Unity 3D是目前非常流行的游戏引擎，上手容易，功能强大，而且跨平台。unity3d教程将从零开始教大家使用Unity，从头开始开发一款小游戏。本课程为Unity 3D入门教程，将实例和理论结合起来，注重实用性， 是一门Unity基础的教程。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"高级"},
	{"course":"Cocos2d-x游戏开发初体验-C++篇","technology":"移动开发","classify":"Cocos2d-x","description":"简介：游戏开发博大精深，在这个后页游时期的手游时代，还在为无法入门游戏行业而烦恼吗？Cocos2d-x就是一款专门为手机游戏打造的开源游戏引擎，够轻量、够简单。在这个不一样的时代，雷哥将带着你走出一个不一样的自己","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"初级"},
	{"course":"Cocos2d-x全民俄罗斯--下","technology":"移动开发","classify":"Cocos2d-x","description":"简介：介绍俄罗斯方块的输入控制逻辑, 方块的移动, 绘制方法, 方块消除, 方块下垂等逻辑, 为增加乐趣, 增加下一块方块提示以及一个漂亮的标题画面","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"中级"},
	{"course":"Cocos2d-x坦克大战--下","technology":"移动开发","classify":"Cocos2d-x","description":"简介：本次课程将为大家介绍敌人的生成和敌人动作的人工智能以及对象交互及阵营处理。最后当然不能少了游戏中最重要的地图编辑器~~！快来开始吧","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"高级"},
	/*-------------------------------------------------------------------------End 移动开发方向-------------------------------------------------------------------------*/

	/*-------------------------------------------------------------------------数据处理方向-------------------------------------------------------------------------*/
	{"course":"mongoDB入门篇","technology":"数据处理","classify":"MongoDB","description":"简介：本课程介绍了mongoDB简单数据库的搭建，从使用方面了解mongoDB的特性与基本的操作，让小伙伴们对mongoDB在业务层的使用有较为详细的了解，可以使用mongoDB完成基本的业务开发。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"初级"},
	{"course":"MongoDB集群之分片技术应用","technology":"数据处理","classify":"MongoDB","description":"简介：从传统关系数据库到现在的\"NOSQL\"数据类型数据库演变过程中，也许总站在处理海量数据的第一线上，如何有效的去除中心化部署库部署接口？如何更高效的存储我们数据资源？本课程教你如何利用Mongodb分片的方式来解决我们数据存储及管理上的困扰。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"高级"},
	{"course":"MongoDB复制集—快速搭建复制集","technology":"数据处理","classify":"MongoDB","description":"简介：基础理论固然重要，在程序员的世界，实战才是王道。为了让大家对复制集有个更直观的认识，必须亲自动手，快速搭建一套属于自己的复制集。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"中级"},
	{"course":"Oracle数据库开发必备利器之SQL基础","technology":"数据处理","classify":"Oracle","description":"简介：Oracle中的函数主要为了方便数据的统计以及处理查询结果。本课程主要介绍Oracle中的常用函数，包括数值函数、字符函数、日期函数和转换函数，并且介绍了这些函数如何在查询中应用。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"初级"},
	{"course":"2015 Oracle技术嘉年华","technology":"数据处理","classify":"Oracle","description":"简介：本课程精选 ACOUG 年度盛会 2015 Oracle 技术嘉年华活动中精彩演讲内容，包括Oracle、MySQL、大数据、高可用容灾安全、数据库云架构、数据标准化及数据建模、行业客户最佳应用实践。由国内顶级数据库专家现场实践操作的 Hands-On Lab 动手培训，让大家尽情享用技术盛宴！","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"高级"},
	{"course":"MyCAT入门及应用","technology":"数据处理","classify":"MySQL","description":"简介：本课程从实际生产环境应用MyCAT入手，讲解MyCAT的基础知识和MyCAT的基本应用操作，本课程的目标就是“看得懂、学得会、做得出”，为后续的学习打下夯实的基础。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"初级"},
	{"course":"MySQL开发技巧（二）","technology":"数据处理","classify":"MySQL","description":"简介：MySQL教程，开发技巧（一）告诉你一个不懂SQL技巧的程序员不是一个好程序员。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"中级"},
	{"course":"数据库设计那些事","technology":"数据处理","classify":"MySQL","description":"简介：数据库作为大多数应用的存储组件，对程序猿所开发的程序是否可以稳定高效的运行起着至关重要的作用。本课程从数据库设计的基本理论入手结合简单的实例，简单明了的告诉您如何设计出一个简洁明了同时又高效稳定的数据库结构。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"高级"},
	{"course":"SQL Server基础--T-SQL语句","technology":"数据处理","classify":"SQL Server","description":"简介：本教程通过对微软SQL Server数据库工具的介绍以及关系型数据库的理解，分析讲解TSQL的基本查询语句和基本用法。其中穿插大量一线实例讲解。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"初级"},
	/*-------------------------------------------------------------------------End 数据处理方向-------------------------------------------------------------------------*/

	/*-------------------------------------------------------------------------大数据&云计算方向-------------------------------------------------------------------------*/
	{"course":"AWS云计算—AWS云上的大数据分析","technology":"大数据&云计算","classify":"大数据","description":"简介：本次大数据专场带你了解基于 AWS 的大数据存储、实时计算与分析, 以及机器学习的相关技术，实现业务洞察，用数据驱动业务和技术创新，提高企业的竞争力，并实现数据的变现。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"高级"},
	{"course":"Hadoop基础及演练","technology":"大数据&云计算","classify":"大数据","description":"简介：在大数据日益火爆的今天，很多猿友都将其作为自己以后的职业方向，本门课程本着细化提取概念点并逐步应用的原则，对大数据生态做了简单的介绍并着重的讲述了开源大数据框架Hadoop的使用和原理。并对Hadoop生态圈的其他开源项目做了简单的介绍，以帮助我们快速的构建大数据的知识图谱。另外讲师的实战课《HBase+SpringBoot实战分布式文件存储》已经上线，有兴趣的小伙伴可以进行深入学习~","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"初级"},
	{"course":"Hadoop进阶","technology":"大数据&云计算","classify":"大数据","description":"简介：本课程首页介绍了hadoop架构体系，包括NameNode和DataNode的作用；然后介绍了MapReduce作业的中间过程和原理，包括缓存的使用，相关参数的性能调优；之后介绍了如何运用MapReduce实现矩阵相乘，并且实现简单的推荐算法","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"中级"},
	{"course":"AWS云计算—混合架构&DevOps深度实践","technology":"大数据&云计算","classify":"云计算","description":"简介：本次架构设计技术专场带你了看Amazon 中国研发中心首席架构师讲解 Microservice & Severless架构；看Musically、 Red Hat、上海数慧等在AWS云上的架构设计技术干货分享。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"中级"},
	{"course":"AWS云服务介绍-Amazon Aurora","technology":"大数据&云计算","classify":"云计算","description":"简介：本课程主要讲解2017年度AWS在中国区的新服务介绍，包括Amazon Redshift Spectrum、Amazon Aurora、AWS CodeDeploy、Jenkins 等服务。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"初级"},
	{"course":"AWS云-深度学习&机器学习的AI业务应用","technology":"大数据&云计算","classify":"云计算","description":"简介：最炙手可热的前沿技术专题，本次人工智能技术专场带你了解如何将深度学习算法运用于图像识别、语音识别、自然语言处理等等领域，通过AWS运算平台向您的客户提供服务","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"高级"},
	{"course":"DevOps和云计算初识","technology":"大数据&云计算","classify":"云计算","description":"简介：DevOps几乎是和云计算同一时间出现在IT行业，没有云平台的弹性和按需资源分配，DevOps就没有办法落地。二者的出现彻底将瀑布式开发甚至Agile敏捷扫入历史的废墟，以AWS为首的西方公司已经可以做到每天上千次的迭代和变更，这些都是技术发展的结果。本课程从一个简单的网站开发部署上线，变更，监控，自恢复等等方面简单介绍利用阿里云平台如何践行简单的DevOps。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"高级"},
	{"course":"Docker入门","technology":"大数据&云计算","classify":"云计算","description":"简介：本课程从最基础的安装开始，通过大量的实际操作循序渐进地介绍Docker基本知识。从最基本的镜像、容器开始，学习Dockerfile编写，容器操作，到完成一个多容器的应用。","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"初级"},
	{"course":"最新Openstack技术和实战","technology":"大数据&云计算","classify":"云计算","description":"简介：最新openstack技术解析","price":1,"score":60,"attention":120,"teacher":"Lnation","imgCover":"images/c.jpg","img":"images/img_01.jpg","nodus":"中级"}
	/*-------------------------------------------------------------------------End 大数据&云计算方向-------------------------------------------------------------------------*/
];